"""promotions

Revision ID: 3443c5a46879
Revises: c2d3e4f5a6b7
Create Date: 2026-08-14 21:59:59.224112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3443c5a46879'
down_revision: Union[str, None] = 'c2d3e4f5a6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('PERCENTAGE_DISCOUNT', 'FIXED_DISCOUNT', 'SPECIAL_PRICE', 'BUY_X_GET_Y', name='promotiontype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'CANCELLED', name='promotionstatus', native_enum=False), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('percentage_value', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fixed_discount_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('special_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('buy_quantity', sa.Integer(), nullable=True),
    sa.Column('pay_quantity', sa.Integer(), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('published_by', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotions_store_id'), 'promotions', ['store_id'], unique=False)
    op.create_table('promotion_branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promotion_id', sa.Integer(), nullable=False),
    sa.Column('store_branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_branch_id'], ['store_branches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promotion_id', 'store_branch_id', name='uq_promotion_branches')
    )
    op.create_index(op.f('ix_promotion_branches_promotion_id'), 'promotion_branches', ['promotion_id'], unique=False)
    op.create_index(op.f('ix_promotion_branches_store_branch_id'), 'promotion_branches', ['store_branch_id'], unique=False)
    op.create_table('promotion_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promotion_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promotion_id', 'product_id', name='uq_promotion_products')
    )
    op.create_index(op.f('ix_promotion_products_product_id'), 'promotion_products', ['product_id'], unique=False)
    op.create_index(op.f('ix_promotion_products_promotion_id'), 'promotion_products', ['promotion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_promotion_products_promotion_id'), table_name='promotion_products')
    op.drop_index(op.f('ix_promotion_products_product_id'), table_name='promotion_products')
    op.drop_table('promotion_products')
    op.drop_index(op.f('ix_promotion_branches_store_branch_id'), table_name='promotion_branches')
    op.drop_index(op.f('ix_promotion_branches_promotion_id'), table_name='promotion_branches')
    op.drop_table('promotion_branches')
    op.drop_index(op.f('ix_promotions_store_id'), table_name='promotions')
    op.drop_table('promotions')
    # ### end Alembic commands ###
