"""coupons

Revision ID: fe1b7ea48087
Revises: 3443c5a46879
Create Date: 2026-08-15 15:01:21.703755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe1b7ea48087'
down_revision: Union[str, None] = '3443c5a46879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('normalized_code', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('PERCENTAGE_DISCOUNT', 'FIXED_AMOUNT', name='coupontype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'CANCELLED', name='couponstatus', native_enum=False), nullable=False),
    sa.Column('percentage_value', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fixed_amount_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('applies_to_entire_purchase', sa.Boolean(), nullable=False),
    sa.Column('applies_to_all_branches', sa.Boolean(), nullable=False),
    sa.Column('minimum_purchase_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('maximum_discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_redemptions_total', sa.Integer(), nullable=True),
    sa.Column('max_redemptions_per_user', sa.Integer(), nullable=True),
    sa.Column('is_stackable', sa.Boolean(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('published_by', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'normalized_code', name='uq_coupons_store_normalized_code')
    )
    op.create_index(op.f('ix_coupons_normalized_code'), 'coupons', ['normalized_code'], unique=False)
    op.create_index(op.f('ix_coupons_store_id'), 'coupons', ['store_id'], unique=False)
    op.create_table('coupon_branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('store_branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_branch_id'], ['store_branches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coupon_id', 'store_branch_id', name='uq_coupon_branches')
    )
    op.create_index(op.f('ix_coupon_branches_coupon_id'), 'coupon_branches', ['coupon_id'], unique=False)
    op.create_index(op.f('ix_coupon_branches_store_branch_id'), 'coupon_branches', ['store_branch_id'], unique=False)
    op.create_table('coupon_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coupon_id', 'product_id', name='uq_coupon_products')
    )
    op.create_index(op.f('ix_coupon_products_coupon_id'), 'coupon_products', ['coupon_id'], unique=False)
    op.create_index(op.f('ix_coupon_products_product_id'), 'coupon_products', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coupon_products_product_id'), table_name='coupon_products')
    op.drop_index(op.f('ix_coupon_products_coupon_id'), table_name='coupon_products')
    op.drop_table('coupon_products')
    op.drop_index(op.f('ix_coupon_branches_store_branch_id'), table_name='coupon_branches')
    op.drop_index(op.f('ix_coupon_branches_coupon_id'), table_name='coupon_branches')
    op.drop_table('coupon_branches')
    op.drop_index(op.f('ix_coupons_store_id'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_normalized_code'), table_name='coupons')
    op.drop_table('coupons')
    # ### end Alembic commands ###
